[package]
name = "crab-hole"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1"
nohash-hasher = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.27", features = ["parking_lot", "rt-multi-thread", "macros", "net"] }
toml = { package = "basic-toml", version = "0.1" }
trust-dns-proto = "0.22"
trust-dns-server = { version = "0.22", features = ["dnssec-ring", "dns-over-rustls", "dns-over-quic", "dns-over-https"] }
