[package]
name = "crab-hole"
version = "0.1.3"
edition = "2021"
description = "Pi-Hole clone written in rust using trust-dns "
repository = "https://github.com/LuckyTurtleDev/crab-hole"
keywords = ["DNS", "BIND", "named", "dnssec"]
license = "AGPL-3.0-or-later"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md"
]

[dependencies]
anyhow = "1.0.70"
ariadne = "0.2"
async-trait = "0.1"
chumsky = "0.9.2"
directories = "5.0.0"
gotham_restful = { version = "0.8.3", features = ["cors", "openapi"], default-features = false }
log = "0.4.17"
my-env-logger-style = "0.1.0"
nohash-hasher = "0.2.0"
num-format = "0.4.4"
once_cell = { version = "1.17.1", features = ["parking_lot"] }
openapi_type = { version = "0.4", features = ["time"] }
reqwest = { version = "0.11.16", default-features = false, features = ["rustls-tls-webpki-roots"] }
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["serde"] }
tokio = { version = "1.27", features = ["fs", "parking_lot", "rt-multi-thread", "macros", "net"] }
toml = { package = "basic-toml", version = "0.1" }
trust-dns-proto = { version = "0.22", default-features = false }
trust-dns-server = { version = "0.22", default-features = false,  features = ["dnssec-ring", "dns-over-rustls", "dns-over-https-rustls", "dns-over-quic"] }
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
indoc = "2.0.1"
