[package]
name = "crab-hole"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.27.0", features = ["parking_lot", "rt-multi-thread", "macros", "net"] }
trust-dns-server = { version = "0.22.0", features = ["dnssec-ring", "dns-over-rustls"] }
