[blocklist]
include_subdomains = true
lists = [
	"https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts",
	"https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt",
	#"file:///blocked.txt"
]

# optional
[api]
listener = "localhost:8080"
#listener = "unix:///tmp/crab-hole.sock"
# optional (default = false)
show_doc = true # OpenAPI doc loads content from third party websites
# optional
admin_key = "1234"

[[downstream]]
protocol = "udp"
listen = "localhost"
port = 8080

[[downstream]]
protocol = "udp"
listen = "[::]"  #all ipv6 and ipv4 adress
port = 8053

# optional
[upstream.options]
# optional (default = false)
validate = true # use DNSSEC


[[upstream.name_servers]]
ip = "2606:4700:4700::1111"
trust_negative_responses = false
# optional (default = protocol default)
port = 853
type = "tls"
server_name = "1dot1dot1dot1.cloudflare-dns.com"

[[upstream.name_servers]]
ip = "2606:4700:4700::1001"
trust_negative_responses = false
type = "tls"
server_name = "1dot1dot1dot1.cloudflare-dns.com"

[[upstream.name_servers]]
ip = "1.1.1.1"
trust_negative_responses = false
type = "tls"
server_name = "1dot1dot1dot1.cloudflare-dns.com"

[[upstream.name_servers]]
ip = "1.0.0.1"
trust_negative_responses = false
[upstream.name_servers.connections.protocol]
type = "tls"
server_name = "1dot1dot1dot1.cloudflare-dns.com"
