[blocklist]
include_subdomains = true
lists = [
	"https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts",
	"https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt",
	"file:///blocked.txt"
]
# allow domains blocked by the blocklist again
allow_list = ["file:///allowed.txt"]
blocking_mode = "nxdomain" # or use "zero" so client will get 0.0.0.0 or [::] as answer

# optional
[api]
listener = "127.0.0.1:8080"
# to use unix sockets, start listener with `unix://` 
#listener = "unix:///tmp/crab-hole.sock"
# optional (default = false)
show_doc = true # OpenAPI doc loads content from third party websites
# optional
admin_key = "1234"

[[downstream]]
protocol = "udp"
listen = "localhost"
port = 8080

[[downstream]]
protocol = "udp"
listen = "[::]" #all ipv6 and ipv4 adress
port = 8053

[[downstream]]
protocol = "tls"
listen = "[::]"
port = 8054
certificate = "dns.example.com.crt"
key = "dns.example.com.key"
# optional (default = 3000)
timeout_ms = 3000

[[downstream]]
protocol = "https"
listen = "[::]"
port = 8055
certificate = "dns.example.com.crt"
key = "dns.example.com.key"
dns_hostname = "dns.example.com"
# optional (default = 3000)
timeout_ms = 3000

[[downstream]]
protocol = "quic"
listen = "127.0.0.1"
port = 8055
certificate = "dns.example.com.crt"
key = "dns.example.com.key"
# optional (default = 3000)
timeout_ms = 3000

[[downstream]]
protocol = "h3"
listen = "127.0.0.1"
port = 8443
certificate = "dns.example.com.crt"
key = "dns.example.com.key"
dns_hostname = "dns.example.com"
# optional (default = 3000)
timeout_ms = 3000

# optional
[upstream.options]
# optional (default = false)
validate = true # use DNSSEC
# see https://docs.rs/hickory-resolver/0.26.0/hickory_resolver/config/struct.ResolverOpts.html for all options

[[upstream.name_servers]]
ip = "2606:4700:4700::1111"
port = 853
protocol = "tls"
server_name = "1dot1dot1dot1.cloudflare-dns.com"
trust_negative_responses = false
# see https://docs.rs/hickory-resolver/0.26.0/hickory_resolver/config/struct.ResolverOpts.html for all options


[[upstream.name_servers]]
ip = "2606:4700:4700::1001"
protocol = "tls"
server_name = "1dot1dot1dot1.cloudflare-dns.com"
trust_negative_responses = false

[[upstream.name_servers]]
ip = "1.1.1.1"
protocol = "tls"
server_name = "1dot1dot1dot1.cloudflare-dns.com"
trust_negative_responses = false

[[upstream.name_servers]]
ip = "1.0.0.1"
protocol = "tls"
server_name = "1dot1dot1dot1.cloudflare-dns.com"
trust_negative_responses = false