name: Rust

on:
  push:
  pull_request:
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo test --workspace --all-features
        env:
          RUST_BACKTRACE: 1

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  cargo_publish:
    if: ${{ github.event_name == 'release' }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: msrd0/cargo-publish-action@v1
        with: 
          packages: crab-hole
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  
  github_publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - name: install cross
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cross
      - run: cross build --all-features --target armv7-unknown-linux-musleabihf
        env:
          RUST_BACKTRACE: 1
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          path: target
  
  docker:
    runs-on: ubuntu-latest
    needs: [github_publish]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: docker
      uses: LuckyTurtleDev/easy-docker-action@main
      with:
        ghcr_password: ${{ secrets.GITHUB_TOKEN }}
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
        max_parallelism: 1


