name: Rust

on:
  push:
  pull_request:
  release:
    types: [released]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo test --workspace --all-features
        env:
          RUST_BACKTRACE: 1

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  cargo_publish:
    if: ${{ github.event_name == 'release' }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: msrd0/cargo-publish-action@v1
        with: 
          packages: crab-hole
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  
  github_publish_cross:
    strategy:
      matrix:
        target: [i686-unknown-linux-musl, x86_64-unknown-linux-musl, arm-unknown-linux-musleabihf, armv7-unknown-linux-musleabihf, aarch64-unknown-linux-musl,   x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-pc-windows-gnu]
    continue-on-error: true
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - name: install cross
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cross
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Target ${{ matrix.target }} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cross build --release --all-features --target ${{ matrix.target }}
        env:
          RUST_BACKTRACE: 1
      - run: tree
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.target }}"
          path: |
            target/${{ matrix.target }}/release/crab-hole
            target/${{ matrix.target }}/release/crab-hole.exe
      - name: Upload Release Asset Win
        if: ${{ github.event_name == 'release' && contains( matrix.target, 'windows' ) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref }}  target/${{ matrix.target }}/release/crab-hole.exe#${{ matrix.target }}
      - name: Upload Release Asset
        if: ${{ github.event_name == 'release' && !contains(matrix.target, 'windows') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref }}  target/${{ matrix.target }}/release/crab-hole#${{ matrix.target }}
  
  github_publish_x86_64-apple-darwin:
    runs-on: macos-latest
    name: x86_64-apple-darwin
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo build --release --all-features
        env:
          RUST_BACKTRACE: 1
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-apple-darwin
          path: target/release/crab-hole
      - name: Upload Release Asset
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref }}  target/${{ matrix.target }}/release/crab-hole#${{ matrix.target }}
  
  docker:
    runs-on: ubuntu-latest
    needs: [github_publish_cross]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: github_artifacts
    - name: docker
      uses: LuckyTurtleDev/easy-docker-action@main
      with:
        ghcr_password: ${{ secrets.GITHUB_TOKEN }}
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        max_parallelism: 1


