name: Rust

on:
  push:
  pull_request:
  release:
    types: [released]

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - name: install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust check ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo hack check --feature-powerset --at-least-one-of aws-lc-rs,ring --locked
        env:
          RUST_BACKTRACE: 1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update -y && sudo apt-get install -y knot-dnsutils
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - name: install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust test ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo hack test --feature-powerset --at-least-one-of aws-lc-rs,ring --mutually-exclusive-features aws-lc-rs,ring --skip __debug_parser,default,native-roots,webpki-roots --locked -- --include-ignored
        env:
          RUST_BACKTRACE: 1

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  benchmark:
    needs: [check]
    name: bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust Bench ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - name: Run benchmark
        run: cargo +nightly bench

  cargo_publish:
    if: ${{ github.event_name == 'release' }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: msrd0/cargo-publish-action@v1
        with: 
          packages: crab-hole
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  
  cross_build:
    strategy:
      fail-fast: false
      matrix:
        target: 
          - target: aarch64-unknown-linux-musl
            pkg: musl-aarch64
            sysroot: /usr/local/share/rust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl
            include: /usr/aarch64-linux-musl/lib/musl/include/
          - target: aarch64-unknown-linux-gnu
            pkg: aarch64-linux-gnu-glibc
            sysroot: /usr/aarch64-linux-gnu/
            include: /usr/aarch64-linux-gnu/include/
          - target: armv7-unknown-linux-musleabihf
            pkg: musl-aarch64 # hack: we need just the headers, so arch is not important
            sysroot: /usr/local/share/rust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-musleabihf
            include: /usr/aarch64-linux-musl/lib/musl/include/ # wrong arch
          - target: i686-unknown-linux-musl
            pkg: musl
            sysroot: /usr/local/share/rust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-musl
            include: /usr/lib/musl/include
          - target: x86_64-pc-windows-gnu
            pkg: mingw-w64 nasm
            sysroot:
            include:
          - target: x86_64-unknown-linux-gnu
            pkg:
            sysroot:
            include:
          - target: x86_64-unknown-linux-musl
            pkg: musl
            sysroot: /usr/local/share/rust/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-musl
            include: /usr/lib/musl/include
        roots: [native-roots, webpki-roots]
    name: ${{ matrix.target.target }}--${{ matrix.roots }}
    runs-on: ubuntu-latest
    container: quay.io/archlinux/archlinux:base-devel
    env:
      RUSTUP_HOME: /usr/local/share/rust
    needs: [test]
    steps:
      - run: |
          pacman -Syu --noconfirm \
            cargo-auditable \
            clang \
            cmake \
            git \
            llvm \
            lsd \
            mold \
            ninja \
            nodejs \
            python \
            rustup \
            rust-bindgen \
            ${{matrix.target.pkg}}
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.target }}
        id: "rust-toolchain"
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Target ${{ matrix.target.target }} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - name: Build crab-hole
        run: |
          TARGET="${{ matrix.target.target }}" \
          TARGET_SYSROOT="${{ matrix.target.sysroot }}" \
          TARGET_INCLUDE="${{ matrix.target.include }}" \
          ROOTS="${{ matrix.roots }}" \
          .github/workflows/cross_build.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.target.target }}--${{ matrix.roots }}"
          path: |
            target/${{ matrix.target.target }}/release/crab-hole
            target/${{ matrix.target.target }}/release/crab-hole.exe
  
  build_x86_64-apple-darwin:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        roots: [native-roots, webpki-roots]
    name: x86_64-apple-darwin--${{ matrix.roots }}
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - uses: taiki-e/install-action@cargo-auditable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo auditable build --release --no-default-features --features aws-lc-rs,${{ matrix.roots }}
        env:
          RUST_BACKTRACE: 1
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: "x86_64-apple-darwin--${{ matrix.roots }}"
          path: target/release/crab-hole
  
  docker:
    runs-on: ubuntu-latest
    needs: [cross_build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: github_artifacts
    - name: docker
      uses: LuckyTurtleDev/easy-docker-action@main
      with:
        ghcr_password: ${{ secrets.GITHUB_TOKEN }}
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
        max_parallelism: 1
  
  github_publish:
    runs-on: ubuntu-latest
    needs: [cross_build]
    if: ${{ github.event_name == 'release' }}
    steps:
    - name: Checkout repository #needed to get github.event.release.tag_name 
      uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: github_artifacts
    - name: Upload Release Artifacts
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ github.event.release.tag_name }}
      run: |
        for dir in github_artifacts/*; do
          dir=${dir#github_artifacts/}
          cd github_artifacts
          zip -r ${dir}.zip ${dir}
          gh release upload ${RELEASE_NAME} ${dir}.zip
          rm ${dir}.zip
          cd ..
        done
